name: app
description: Demonstrates how to use the waya package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_curiosity: ^4.5.0
  device_preview: ^1.1.0
  flutter_waya:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
