name: app
description: Demonstrates how to use the waya package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_curiosity: ^6.1.0
  device_preview_minus: ^1.0.2
  flutter_waya:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
