name: app
description: Demonstrates how to use the waya package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_curiosity: ^4.2.1
  device_preview: ^1.1.0
  flutter_waya:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
