name: waya
description: Demonstrates how to use the waya package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_curiosity: ^3.3.1
  flutter_localizations:
    sdk: flutter
  flutter_waya:
    path: ../
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
