name: waya
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  oktoast: ^2.3.2
  flutter_waya:
    path: ../


flutter:
  uses-material-design: true
