name: app
description: Demonstrates how to use the waya package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_curiosity: ^6.4.0
  device_preview_minus: ^1.0.8
  fl_extended: ^1.6.0
  flutter_waya:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
