name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 1.16.7
repository: https://github.com/Wayaer/flutter_waya

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  crypto: ^3.0.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.2.1
  flutter_localizations:
    sdk: flutter
  http_parser: ^4.0.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: Icons
      fonts:
        - asset: lib/res/icons.ttf