name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 1.6.3
homepage: https://github.com/Wayaer/flutter_waya

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  crypto: ^3.0.0
    cookie_jar: ^1.0.1
  dio: ^3.0.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http_parser: ^3.1.4
  pull_to_refresh: ^1.6.3
  vector_math: ^2.1.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  fonts:
    - family: Icons
      fonts:
        - asset: lib/res/icons.ttf


