name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 2.1.0+1
repository: https://github.com/Wayaer/flutter_waya

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.2.1
  flutter_staggered_grid_view: ^0.6.1
  http_parser: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Icons
      fonts:
        - asset: lib/res/icons.ttf