name: flutter_waya
description: A new Flutter package.
version: 0.0.1
author: Wayaer <wayaer@foxmail.com>
homepage: https://github.com/Wayaer/flutter_waya

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 添加
    sdk: flutter
  shared_preferences: ^0.5.6
  provider: ^4.0.0
  dio: ^3.0.7
  synchronized: ^2.1.1
  pull_to_refresh: ^1.5.7
  flutter_curiosity:
#    git: https://github.com/Wayaer/flutter_curiosity.git
    path: ../flutter_curiosity
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
#  fonts:
#    - family: Icons
#      fonts:
#        - asset: lib/res/icons.ttf

# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700

