name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 2.0.0
repository: https://github.com/Wayaer/flutter_waya

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  dio: ^3.0.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pull_to_refresh: ^1.6.4

flutter:
  fonts:
    - family: Icons
      fonts:
        - asset: lib/res/icons.ttf