name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 8.6.4
repository: https://github.com/Wayaer/flutter_waya

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:

  flutter:
    sdk: flutter
  easy_refresh: ^3.3.3+1
  path_drawing: ^1.0.1
  collection: ^1.17.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: WayIcons
      fonts:
        - asset: assets/WayIcons.ttf