name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 1.9.2
repository: https://github.com/Wayaer/flutter_waya

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  crypto: ^3.0.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_easyrefresh: ^2.1.8
  flutter_localizations:
    sdk: flutter
  http_parser: ^4.0.0

flutter:
  fonts:
    - family: Icons
      fonts:
        - asset: lib/res/icons.ttf