name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 6.0.1
repository: https://github.com/Wayaer/flutter_waya

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 网络请求
  dio: ^5.1.1
  # md5 加密 Hmac
  crypto: ^3.0.2
  # HTTP相关处理
  http_parser: ^4.0.2
  # 下拉刷新 上拉加载
  easy_refresh: ^3.3.1+1
  # 创建和操作path
  path_drawing: ^1.0.1
  # 瀑布流
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: WayIcons
      fonts:
        - asset: assets/WayIcons.ttf