name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 8.2.0
repository: https://github.com/Wayaer/flutter_waya

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:

  flutter:
    sdk: flutter
  # 下拉刷新 上拉加载
  easy_refresh: ^3.3.2+1
  path_drawing: ^1.0.1
  # 瀑布流
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  fonts:
    - family: WayIcons
      fonts:
        - asset: assets/WayIcons.ttf