name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 1.2.0
author: wayaer <wayaer@foxmail.com>
homepage: https://github.com/Wayaer/flutter_waya

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypto: 2.1.5
  dio: ^3.0.10
  synchronized: ^2.2.0+2
  pull_to_refresh: ^1.6.1
  cookie_jar: ^1.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Icons
      fonts:
        - asset: lib/res/icons.ttf


