name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 1.0.5
author: wayaer <wayaer@foxmail.com>
homepage: https://github.com/Wayaer/flutter_waya

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypto: ^2.1.3
  provider: ^4.1.1
  dio: ^3.0.9
  synchronized: ^2.2.0
  pull_to_refresh: ^1.5.8
  cookie_jar: ^1.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Icons
      fonts:
        - asset: lib/res/icons.ttf


