name: flutter_waya
description: The Flutter UI library contains multiple custom components,compatible with android,web,ios and MAC.
version: 3.3.0+9
repository: https://github.com/Wayaer/flutter_waya

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  easy_refresh: ^3.0.4+2
  flutter_staggered_grid_view: ^0.6.2
  http_parser: ^4.0.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Icons
      fonts:
        - asset: lib/res/icons.ttf